version: '3.7'

services:

  naming-server:
    image: skg5407/microservices-v2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network: